import type {
  ActivityEvent,
  AlertItem,
  AuditLog,
  Conversation,
  Driver,
  Expense,
  FuelRequisition,
  GateEntry,
  InventoryItem,
  InventoryRequisition,
  Notification,
  ProcurementRequest,
  Role,
  Tenant,
  PlatformTenant,
  Company,
  Trip,
  TruckHead,
  TruckTail,
  User,
  WorkOrder,
} from "./types";

/** Deterministic pseudo-random so SSR and client render identically. */
function rng(seed: number) {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) % 4294967296;
    return s / 4294967296;
  };
}
const r = rng(20260812);
const pick = <T,>(arr: readonly T[]) => arr[Math.floor(r() * arr.length)]!;
const int = (min: number, max: number) => Math.floor(min + r() * (max - min + 1));

// Mock Current User Role for RBAC Testing
export const CURRENT_ROLE = "Operations Admin";

const pad = (n: number, w = 3) => String(n).padStart(w, "0");

export const TENANT: Tenant = {
  id: "TEN-001",
  name: "Petroline Transport",
  workspaceId: "PTL-001",
  tenantSlug: "petrolline",
  industry: "Heavy Haulage / Oil & Gas Logistics",
  country: "Nigeria",
  locations: ["Lagos HQ", "Abuja Depot", "Port Harcourt Yard", "Kano Terminal"],
  contactEmail: "operations@petroline.ng",
  contactPhone: "+234 802 118 4420",
};

export const PLATFORM_TENANTS: PlatformTenant[] = [
  {
    id: "tnt_001",
    name: "Petroline Logistics",
    domain: "petroline",
    tenantSlug: "petrolline",
    logo: "/petroline-transparent.png",
    status: "Active",
    activeTrucks: 142,
    totalOrders: 12450,
    joinedAt: "2024-01-15",
  }
];

export const COMPANIES: Company[] = [];

export const WORKSPACES = [
  { id: "PTL-001", name: "Petroline Transport", role: "Operations Admin" },
  { id: "NRT-014", name: "Northrail Haulage", role: "Viewer" },
  { id: "DLT-092", name: "Delta Bulk Logistics", role: "Viewer" },
];

const FIRST = [
  "Emeka", "Ibrahim", "Chinedu", "Musa", "Tunde", "Segun", "Abdul", "Kelechi",
  "Yusuf", "Obinna", "Sadiq", "Femi", "Uche", "Bala", "Nnamdi", "Kabiru",
  "Olamide", "Danjuma", "Ifeanyi", "Suleiman", "Gbenga", "Hassan", "Chika",
  "Aliyu", "Tobi", "Peter", "Michael", "Samuel", "Joseph", "Daniel",
];
const LAST = [
  "Okafor", "Bello", "Adeyemi", "Lawal", "Eze", "Mohammed", "Nwachukwu",
  "Ogunleye", "Danladi", "Umeh", "Balogun", "Sani", "Ikenna", "Yakubu",
  "Ojo", "Garba", "Anyanwu", "Usman", "Adekunle", "Okonkwo",
];

const CITIES = [
  "Lagos", "Abuja", "Port Harcourt", "Kano", "Ibadan", "Warri", "Onitsha",
  "Kaduna", "Benin City", "Enugu", "Calabar", "Jos", "Aba", "Maiduguri",
];
const COORDS: Record<string, [number, number]> = {
  Lagos: [6.5244, 3.3792],
  Abuja: [9.0765, 7.3986],
  "Port Harcourt": [4.8156, 7.0498],
  Kano: [12.0022, 8.592],
  Ibadan: [7.3775, 3.947],
  Warri: [5.5167, 5.75],
  Onitsha: [6.1667, 6.7833],
  Kaduna: [10.5222, 7.4384],
  "Benin City": [6.335, 5.6037],
  Enugu: [6.4584, 7.5464],
  Calabar: [4.9757, 8.3417],
  Jos: [9.8965, 8.8583],
  Aba: [5.1066, 7.3667],
  Maiduguri: [11.8311, 13.151],
};

const CUSTOMERS = [
  "NNPC Retail", "Dangote Cement", "TotalEnergies NG", "Lafarge Africa",
  "Seplat Energy", "Julius Berger", "Chevron Nigeria", "BUA Group",
  "Ardova Plc", "Oando Energy",
];
const CARGO = [
  "PMS 45,000L", "AGO 33,000L", "Bulk Cement 30T", "Drilling Pipes 24T",
  "LPG 20T", "Bitumen 28T", "Base Oil 32,000L", "Construction Aggregate 35T",
];
const TRUCK_TYPES = ["Tanker 45KL", "Tanker 33KL", "Flatbed 40FT", "Tipper 30T", "Low Loader", "Box Trailer"];
const MAKES = ["MAN TGS", "Scania R500", "Mercedes Actros", "Howo A7", "Volvo FH16", "IVECO Stralis"];

export const DRIVERS: Driver[] = [
  {
    "id": "DRV-1",
    "employeeId": "P00851",
    "name": "Musa Garuba",
    "phone": "09075501315",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-410601",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "P004 - FKJ753XR",
    "currentTripId": null,
    "tripsCompleted": 0,
    "safetyScore": 89,
    "initials": "MG"
  },
  {
    "id": "DRV-2",
    "employeeId": "P00971",
    "name": "Muhammed Musa Aliu",
    "phone": "07030511347",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-403876",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 4,
    "status": "Available",
    "assignedTruck": "P005 - SBG566XR",
    "currentTripId": null,
    "tripsCompleted": 2,
    "safetyScore": 80,
    "initials": "MM"
  },
  {
    "id": "DRV-3",
    "employeeId": "P01019",
    "name": "Hassan Abdullahi",
    "phone": "08145511587",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-527610",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P007 - AAA494XA",
    "currentTripId": null,
    "tripsCompleted": 31,
    "safetyScore": 88,
    "initials": "HA"
  },
  {
    "id": "DRV-4",
    "employeeId": "P01018",
    "name": "Muhammad Musa",
    "phone": "09038840110",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-274096",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P009 - MUS10XB",
    "currentTripId": null,
    "tripsCompleted": 39,
    "safetyScore": 82,
    "initials": "MM"
  },
  {
    "id": "DRV-5",
    "employeeId": "P00935",
    "name": "Umar Abubakar",
    "phone": "07083922957",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-480234",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "P011 - KSF928XQ",
    "currentTripId": null,
    "tripsCompleted": 38,
    "safetyScore": 90,
    "initials": "UA"
  },
  {
    "id": "DRV-6",
    "employeeId": "P01009",
    "name": "Mohammed Dauda",
    "phone": "08153465033",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-396817",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "P012 - KSF929XQ",
    "currentTripId": null,
    "tripsCompleted": 5,
    "safetyScore": 97,
    "initials": "MD"
  },
  {
    "id": "DRV-7",
    "employeeId": "P00848",
    "name": "Adeyemi Sulaiman",
    "phone": "09050715348",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-638508",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "P018 - JHN402XA",
    "currentTripId": null,
    "tripsCompleted": 20,
    "safetyScore": 99,
    "initials": "AS"
  },
  {
    "id": "DRV-8",
    "employeeId": "P01010",
    "name": "Abubakar Abdullai",
    "phone": "07049990982",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-721897",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P015 - SBG757ZY",
    "currentTripId": null,
    "tripsCompleted": 21,
    "safetyScore": 87,
    "initials": "AA"
  },
  {
    "id": "DRV-9",
    "employeeId": "P00989",
    "name": "Yusuf Muhammed",
    "phone": "08120760563",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-884590",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "P034 - MKA982XW",
    "currentTripId": null,
    "tripsCompleted": 32,
    "safetyScore": 83,
    "initials": "YM"
  },
  {
    "id": "DRV-10",
    "employeeId": "P00934",
    "name": "Zakari Sanusi",
    "phone": "07040378057",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-918952",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P017 - GRR171XA ",
    "currentTripId": null,
    "tripsCompleted": 37,
    "safetyScore": 92,
    "initials": "ZS"
  },
  {
    "id": "DRV-11",
    "employeeId": "P00997",
    "name": "Muktar Aliyu",
    "phone": "07069332210",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-685976",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 4,
    "status": "Available",
    "assignedTruck": "P018 - JHN402XA",
    "currentTripId": null,
    "tripsCompleted": 44,
    "safetyScore": 91,
    "initials": "MA"
  },
  {
    "id": "DRV-12",
    "employeeId": "P00909",
    "name": "Oseni Ahmed",
    "phone": "08052479219",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-114434",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "P018 - JHN402XA",
    "currentTripId": null,
    "tripsCompleted": 9,
    "safetyScore": 99,
    "initials": "OA"
  },
  {
    "id": "DRV-13",
    "employeeId": "P00879",
    "name": "Umoru Abdulmumuni",
    "phone": "08109223925",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-909272",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P021 - JHN506XA",
    "currentTripId": null,
    "tripsCompleted": 33,
    "safetyScore": 85,
    "initials": "UA"
  },
  {
    "id": "DRV-14",
    "employeeId": "P01006",
    "name": "Yahaya Alhassan",
    "phone": "09126144854",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-952742",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P022 - ZAR513XM",
    "currentTripId": null,
    "tripsCompleted": 17,
    "safetyScore": 88,
    "initials": "YA"
  },
  {
    "id": "DRV-15",
    "employeeId": "P00944",
    "name": "Junbrin Tela Musa",
    "phone": "07062551299",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-151586",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "P023 - MKR508ZP",
    "currentTripId": null,
    "tripsCompleted": 41,
    "safetyScore": 94,
    "initials": "JT"
  },
  {
    "id": "DRV-16",
    "employeeId": "P00991",
    "name": "Jarfar Shuaibu",
    "phone": "08051319087",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-757680",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "P024 - MKA434XV",
    "currentTripId": null,
    "tripsCompleted": 9,
    "safetyScore": 98,
    "initials": "JS"
  },
  {
    "id": "DRV-17",
    "employeeId": "P00891",
    "name": "Mohammed Ibrahim",
    "phone": "0912430289",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-746275",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 4,
    "status": "Available",
    "assignedTruck": "P026 - BNG751ZF",
    "currentTripId": null,
    "tripsCompleted": 6,
    "safetyScore": 82,
    "initials": "MI"
  },
  {
    "id": "DRV-18",
    "employeeId": "P00963",
    "name": "Maniru Auwalu",
    "phone": "09034718790",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-505079",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 3,
    "status": "Available",
    "assignedTruck": "P027 - GML365XX",
    "currentTripId": null,
    "tripsCompleted": 32,
    "safetyScore": 93,
    "initials": "MA"
  },
  {
    "id": "DRV-19",
    "employeeId": "P00910",
    "name": "Sani Mohammed",
    "phone": "09054677988",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-650073",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P028 - GML368XX",
    "currentTripId": null,
    "tripsCompleted": 48,
    "safetyScore": 90,
    "initials": "SM"
  },
  {
    "id": "DRV-20",
    "employeeId": "P00990",
    "name": "Musa Ibrahim",
    "phone": "09025182000",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-987349",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "P029 - GRK177XA",
    "currentTripId": null,
    "tripsCompleted": 35,
    "safetyScore": 92,
    "initials": "MI"
  },
  {
    "id": "DRV-21",
    "employeeId": "P00966",
    "name": "Hassan Mohammed",
    "phone": "08089364110",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-838715",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P018 - JHN402XA",
    "currentTripId": null,
    "tripsCompleted": 30,
    "safetyScore": 98,
    "initials": "HM"
  },
  {
    "id": "DRV-22",
    "employeeId": "P00867",
    "name": "Ahmadu Ali",
    "phone": "07047558884",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-480577",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 12,
    "safetyScore": 89,
    "initials": "AA"
  },
  {
    "id": "DRV-23",
    "employeeId": "P00293",
    "name": "Mohammed",
    "phone": "08053160259",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-331532",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 14,
    "safetyScore": 91,
    "initials": "M"
  },
  {
    "id": "DRV-24",
    "employeeId": "P01001",
    "name": "Adamu Muhammed",
    "phone": "07016779738",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-533791",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 11,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 45,
    "safetyScore": 83,
    "initials": "AM"
  },
  {
    "id": "DRV-25",
    "employeeId": "P01005",
    "name": "Abdullahi Adamu",
    "phone": "09055912576",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-316808",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 3,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 34,
    "safetyScore": 95,
    "initials": "AA"
  },
  {
    "id": "DRV-26",
    "employeeId": "P00983",
    "name": "Umar Adamu",
    "phone": "07016779738",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-667783",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 3,
    "safetyScore": 91,
    "initials": "UA"
  },
  {
    "id": "DRV-27",
    "employeeId": "P01001",
    "name": "Adamu Isah",
    "phone": "07060804674",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-999118",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P038 - RJA344XA",
    "currentTripId": null,
    "tripsCompleted": 3,
    "safetyScore": 97,
    "initials": "AI"
  },
  {
    "id": "DRV-28",
    "employeeId": "P00979",
    "name": "Usman Adamu",
    "phone": "09024703369",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-312890",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 3,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 23,
    "safetyScore": 96,
    "initials": "UA"
  },
  {
    "id": "DRV-29",
    "employeeId": "P00967",
    "name": "Ali Mohammed",
    "phone": "08030573776",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-668696",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 4,
    "safetyScore": 89,
    "initials": "AM"
  },
  {
    "id": "DRV-30",
    "employeeId": "P00501",
    "name": "Mohammed Musa",
    "phone": "08143180442",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-522568",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "P041 - KNT783XP",
    "currentTripId": null,
    "tripsCompleted": 13,
    "safetyScore": 99,
    "initials": "MM"
  },
  {
    "id": "DRV-31",
    "employeeId": "P00981",
    "name": "Aderinde Muritala",
    "phone": "08127653596",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-399473",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 4,
    "status": "Available",
    "assignedTruck": "P005 - SBG566XR",
    "currentTripId": null,
    "tripsCompleted": 0,
    "safetyScore": 99,
    "initials": "AM"
  },
  {
    "id": "DRV-32",
    "employeeId": "P00974",
    "name": "Mudasiru Lawal",
    "phone": "08064538189",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-882416",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "P104 - KRD532YM",
    "currentTripId": null,
    "tripsCompleted": 17,
    "safetyScore": 80,
    "initials": "ML"
  },
  {
    "id": "DRV-33",
    "employeeId": "P00508",
    "name": "Umar Badamas",
    "phone": "08081732225",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-763193",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P040 - KNT781XP",
    "currentTripId": null,
    "tripsCompleted": 9,
    "safetyScore": 84,
    "initials": "UB"
  },
  {
    "id": "DRV-34",
    "employeeId": "P00950",
    "name": "Hassan Isa",
    "phone": "09073416980",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-454309",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 3,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 23,
    "safetyScore": 82,
    "initials": "HI"
  },
  {
    "id": "DRV-35",
    "employeeId": "P00806",
    "name": "Mohammed Shaibu",
    "phone": "08167314570",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-897940",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "P068 - GGE90YK",
    "currentTripId": null,
    "tripsCompleted": 45,
    "safetyScore": 92,
    "initials": "MS"
  },
  {
    "id": "DRV-36",
    "employeeId": "P00985",
    "name": "Umbali Halilu",
    "phone": "09065243858",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-438444",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 27,
    "safetyScore": 84,
    "initials": "UH"
  },
  {
    "id": "DRV-37",
    "employeeId": "P00853",
    "name": "Lukman Ajasa",
    "phone": "08139495496",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-203365",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 18,
    "safetyScore": 92,
    "initials": "LA"
  },
  {
    "id": "DRV-38",
    "employeeId": "P01020",
    "name": "Zakari Mohammed",
    "phone": "08060347314",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-538006",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 22,
    "safetyScore": 95,
    "initials": "ZM"
  },
  {
    "id": "DRV-39",
    "employeeId": "P00959",
    "name": "Hassan Abdullahi",
    "phone": "07042236908",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-798353",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 11,
    "status": "Available",
    "assignedTruck": "P025 - MGN899ZJ",
    "currentTripId": null,
    "tripsCompleted": 17,
    "safetyScore": 90,
    "initials": "HA"
  },
  {
    "id": "DRV-40",
    "employeeId": "P01016",
    "name": "Maude Umar",
    "phone": "07042236908",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-916184",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 43,
    "safetyScore": 98,
    "initials": "MU"
  },
  {
    "id": "DRV-41",
    "employeeId": "P00221",
    "name": "Ibrahim Garuba",
    "phone": "081666697246",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-906969",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P055 - GGE85YK",
    "currentTripId": null,
    "tripsCompleted": 20,
    "safetyScore": 83,
    "initials": "IG"
  },
  {
    "id": "DRV-42",
    "employeeId": "P00883",
    "name": "Isiaka Haruna",
    "phone": "07017887954",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-561175",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 3,
    "status": "Available",
    "assignedTruck": "P056 - GGE96YK",
    "currentTripId": null,
    "tripsCompleted": 28,
    "safetyScore": 85,
    "initials": "IH"
  },
  {
    "id": "DRV-43",
    "employeeId": "P00747",
    "name": "Mohammed Rabiu G",
    "phone": "07036442300",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-907749",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P214",
    "currentTripId": null,
    "tripsCompleted": 21,
    "safetyScore": 87,
    "initials": "MR"
  },
  {
    "id": "DRV-44",
    "employeeId": "DRV-44",
    "name": "Abdullazeez Mohammed",
    "phone": "08168010858",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-229524",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 11,
    "safetyScore": 94,
    "initials": "AM"
  },
  {
    "id": "DRV-45",
    "employeeId": "P00859",
    "name": "Yahya Aliyu",
    "phone": "08052965606",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-346149",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P059 - GGE91YK",
    "currentTripId": null,
    "tripsCompleted": 27,
    "safetyScore": 97,
    "initials": "YA"
  },
  {
    "id": "DRV-46",
    "employeeId": "P00952",
    "name": "Hamisu Isiya",
    "phone": "08035944433",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-139328",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 18,
    "safetyScore": 98,
    "initials": "HI"
  },
  {
    "id": "DRV-47",
    "employeeId": "P00733",
    "name": "Shamailu Dauda",
    "phone": "08078823106",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-927038",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "P061 - GGE101YK",
    "currentTripId": null,
    "tripsCompleted": 39,
    "safetyScore": 95,
    "initials": "SD"
  },
  {
    "id": "DRV-48",
    "employeeId": "P00868",
    "name": "Idowu Adekola",
    "phone": "08123151938",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-230275",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P036 - BDA887XA",
    "currentTripId": null,
    "tripsCompleted": 14,
    "safetyScore": 86,
    "initials": "IA"
  },
  {
    "id": "DRV-49",
    "employeeId": "P00930",
    "name": "Monsuru Lamidi",
    "phone": "07048292784",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-803069",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 11,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 15,
    "safetyScore": 96,
    "initials": "ML"
  },
  {
    "id": "DRV-50",
    "employeeId": "P00970",
    "name": "Mohammed Auwalu",
    "phone": "0912951883",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-756913",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "P064 - GGE105YK",
    "currentTripId": null,
    "tripsCompleted": 40,
    "safetyScore": 92,
    "initials": "MA"
  },
  {
    "id": "DRV-51",
    "employeeId": "P00856",
    "name": "Abdullahi Abubakar P",
    "phone": "08158607133",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-559648",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P065 - GGE95YK",
    "currentTripId": null,
    "tripsCompleted": 38,
    "safetyScore": 89,
    "initials": "AA"
  },
  {
    "id": "DRV-52",
    "employeeId": "P00992",
    "name": "Shafiu Haruna",
    "phone": "09055288341",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-459058",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 15,
    "safetyScore": 97,
    "initials": "SH"
  },
  {
    "id": "DRV-53",
    "employeeId": "P00911",
    "name": "Salisu Adamu",
    "phone": "08065879393",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-586062",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "P067 - GGE99YK",
    "currentTripId": null,
    "tripsCompleted": 4,
    "safetyScore": 82,
    "initials": "SA"
  },
  {
    "id": "DRV-54",
    "employeeId": "P00831",
    "name": "Bashiru Yahaya",
    "phone": "08120347796",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-464796",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "P030 - DKA317XQ",
    "currentTripId": null,
    "tripsCompleted": 14,
    "safetyScore": 90,
    "initials": "BY"
  },
  {
    "id": "DRV-55",
    "employeeId": "DRV-55",
    "name": "Idris Nuhu",
    "phone": "08057214692",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-944868",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "P042 - KNT785XP",
    "currentTripId": null,
    "tripsCompleted": 33,
    "safetyScore": 87,
    "initials": "IN"
  },
  {
    "id": "DRV-56",
    "employeeId": "P00958",
    "name": "Usman Haruna",
    "phone": "07010327422",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-570410",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 14,
    "safetyScore": 92,
    "initials": "UH"
  },
  {
    "id": "DRV-57",
    "employeeId": "P00984",
    "name": "Saidu Usaini",
    "phone": "07068268909",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-638117",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 17,
    "safetyScore": 82,
    "initials": "SU"
  },
  {
    "id": "DRV-58",
    "employeeId": "P00502",
    "name": "Dogo Danladi",
    "phone": "08135883555",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-392096",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "P074 - APP861YL",
    "currentTripId": null,
    "tripsCompleted": 49,
    "safetyScore": 94,
    "initials": "DD"
  },
  {
    "id": "DRV-59",
    "employeeId": "P00906",
    "name": "Samsudeen Yarema",
    "phone": "07078667189 / 08150457838",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-504127",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 24,
    "safetyScore": 91,
    "initials": "SY"
  },
  {
    "id": "DRV-60",
    "employeeId": "P00560",
    "name": "Abdullahi Haruna",
    "phone": "08035334386",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-510329",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 35,
    "safetyScore": 97,
    "initials": "AH"
  },
  {
    "id": "DRV-61",
    "employeeId": "P00885",
    "name": "Buba Hammah",
    "phone": "08067685525",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-681766",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "P015 - SBG757ZY",
    "currentTripId": null,
    "tripsCompleted": 28,
    "safetyScore": 85,
    "initials": "BH"
  },
  {
    "id": "DRV-62",
    "employeeId": "P00516",
    "name": "Sanusi Mohammed",
    "phone": "08152808911",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-957597",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "P078 - KRD280YL",
    "currentTripId": null,
    "tripsCompleted": 16,
    "safetyScore": 96,
    "initials": "SM"
  },
  {
    "id": "DRV-63",
    "employeeId": "P00956",
    "name": "Abdullahi Jidda",
    "phone": "07041243554",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-851031",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P079 - APP860YL",
    "currentTripId": null,
    "tripsCompleted": 32,
    "safetyScore": 84,
    "initials": "AJ"
  },
  {
    "id": "DRV-64",
    "employeeId": "DRV-64",
    "name": "Usman B Garba",
    "phone": "08034337052",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-236410",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 3,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 46,
    "safetyScore": 95,
    "initials": "UB"
  },
  {
    "id": "DRV-65",
    "employeeId": "P00855",
    "name": "Mogaji Issa",
    "phone": "08035446246",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-885357",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P081 - FST570YL",
    "currentTripId": null,
    "tripsCompleted": 6,
    "safetyScore": 95,
    "initials": "MI"
  },
  {
    "id": "DRV-66",
    "employeeId": "P00704",
    "name": "Ganiyu Semiu",
    "phone": "08163467547",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-177643",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "P082 - FST569YL",
    "currentTripId": null,
    "tripsCompleted": 19,
    "safetyScore": 95,
    "initials": "GS"
  },
  {
    "id": "DRV-67",
    "employeeId": "P00841",
    "name": "Salihu Mohammed",
    "phone": "08088574033",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-475442",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "P083 - FST567YL",
    "currentTripId": null,
    "tripsCompleted": 32,
    "safetyScore": 94,
    "initials": "SM"
  },
  {
    "id": "DRV-68",
    "employeeId": "P00044",
    "name": "Ahmadu Illiyasu",
    "phone": "08136819489",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-651864",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P060 - GGE103YK",
    "currentTripId": null,
    "tripsCompleted": 42,
    "safetyScore": 89,
    "initials": "AI"
  },
  {
    "id": "DRV-69",
    "employeeId": "P00226",
    "name": "Abdullahi Ibrahim",
    "phone": "07039997235",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-209004",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P017 - GRR171XA ",
    "currentTripId": null,
    "tripsCompleted": 11,
    "safetyScore": 92,
    "initials": "AI"
  },
  {
    "id": "DRV-70",
    "employeeId": "P00975",
    "name": "Samaila Musa",
    "phone": "07033333176",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-388199",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "P109 - AKD320YM",
    "currentTripId": null,
    "tripsCompleted": 19,
    "safetyScore": 91,
    "initials": "SM"
  },
  {
    "id": "DRV-71",
    "employeeId": "P00278",
    "name": "Muktar Ashimuyi",
    "phone": "08134557651",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-470823",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 4,
    "status": "Available",
    "assignedTruck": "P045 - GGE100YK",
    "currentTripId": null,
    "tripsCompleted": 49,
    "safetyScore": 83,
    "initials": "MA"
  },
  {
    "id": "DRV-72",
    "employeeId": "P00318",
    "name": "Sanni Garuba",
    "phone": "08039689245",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-683908",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P071 - APP858YL",
    "currentTripId": null,
    "tripsCompleted": 42,
    "safetyScore": 92,
    "initials": "SG"
  },
  {
    "id": "DRV-73",
    "employeeId": "P00251",
    "name": "Abdullahi Abubakar",
    "phone": "08035394966",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-232671",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 4,
    "status": "Available",
    "assignedTruck": "P073 - APP857YL",
    "currentTripId": null,
    "tripsCompleted": 40,
    "safetyScore": 99,
    "initials": "AA"
  },
  {
    "id": "DRV-74",
    "employeeId": "P00259",
    "name": "Bashiru Abdullahi",
    "phone": "07065639344",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-906775",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "P080 - FST568YL",
    "currentTripId": null,
    "tripsCompleted": 21,
    "safetyScore": 86,
    "initials": "BA"
  },
  {
    "id": "DRV-75",
    "employeeId": "P00102",
    "name": "Danladi Adamu",
    "phone": "08100310555",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-583479",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "P076 - APP863YL",
    "currentTripId": null,
    "tripsCompleted": 32,
    "safetyScore": 99,
    "initials": "DA"
  },
  {
    "id": "DRV-76",
    "employeeId": "P00063",
    "name": "Yakubu Abubakar Biu",
    "phone": "08068030799",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-420494",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 11,
    "status": "Available",
    "assignedTruck": "P084 - KRD279YL",
    "currentTripId": null,
    "tripsCompleted": 37,
    "safetyScore": 89,
    "initials": "YA"
  },
  {
    "id": "DRV-77",
    "employeeId": "P00311",
    "name": "Muhammed Khalid",
    "phone": "09032514626",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-600368",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P048 - GGE86YK",
    "currentTripId": null,
    "tripsCompleted": 40,
    "safetyScore": 84,
    "initials": "MK"
  },
  {
    "id": "DRV-78",
    "employeeId": "DRV-78",
    "name": "Adewu (name unclear in scan)",
    "phone": "0703...(unreadable)",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-397606",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "P053 - GGE97YK",
    "currentTripId": null,
    "tripsCompleted": 7,
    "safetyScore": 94,
    "initials": "A("
  },
  {
    "id": "DRV-79",
    "employeeId": "P00672",
    "name": "Lawan Tijani",
    "phone": "07071941219",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-845158",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 11,
    "status": "Available",
    "assignedTruck": "P049 - GGE104YK",
    "currentTripId": null,
    "tripsCompleted": 39,
    "safetyScore": 99,
    "initials": "LT"
  },
  {
    "id": "DRV-80",
    "employeeId": "P01015",
    "name": "Baballa Salisu",
    "phone": "08106764460",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-103933",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 43,
    "safetyScore": 84,
    "initials": "BS"
  },
  {
    "id": "DRV-81",
    "employeeId": "P00128",
    "name": "Bala Garuba",
    "phone": "07032047157",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-759039",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P070 - GGE93YK",
    "currentTripId": null,
    "tripsCompleted": 15,
    "safetyScore": 81,
    "initials": "BG"
  },
  {
    "id": "DRV-82",
    "employeeId": "P00716",
    "name": "Ibrahim Abubakar",
    "phone": "07010709327",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-632603",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P057 - GGE87YK",
    "currentTripId": null,
    "tripsCompleted": 1,
    "safetyScore": 83,
    "initials": "IA"
  },
  {
    "id": "DRV-83",
    "employeeId": "P00886",
    "name": "Illiasu Mohammed",
    "phone": "08034593978",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-859560",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "P072",
    "currentTripId": null,
    "tripsCompleted": 46,
    "safetyScore": 92,
    "initials": "IM"
  },
  {
    "id": "DRV-84",
    "employeeId": "P00069",
    "name": "Ado Sanni",
    "phone": "08132172750",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-396942",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 10,
    "status": "Available",
    "assignedTruck": "P085 - APP589YL",
    "currentTripId": null,
    "tripsCompleted": 10,
    "safetyScore": 84,
    "initials": "AS"
  },
  {
    "id": "DRV-85",
    "employeeId": "P00017",
    "name": "Saidu Sule",
    "phone": "08119310521",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-477509",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "P083 - FST567YL",
    "currentTripId": null,
    "tripsCompleted": 34,
    "safetyScore": 84,
    "initials": "SS"
  },
  {
    "id": "DRV-86",
    "employeeId": "P00866",
    "name": "Yusuf Mohammed",
    "phone": "07050862772",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-979528",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 4,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 29,
    "safetyScore": 98,
    "initials": "YM"
  },
  {
    "id": "DRV-87",
    "employeeId": "P00903",
    "name": "Abdullahi Adamu",
    "phone": "09064472332",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-885042",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "P044 - GGE109YK",
    "currentTripId": null,
    "tripsCompleted": 31,
    "safetyScore": 80,
    "initials": "AA"
  },
  {
    "id": "DRV-88",
    "employeeId": "P00933",
    "name": "Ibrahim Adamu",
    "phone": "08160057747",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-695004",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 48,
    "safetyScore": 94,
    "initials": "IA"
  },
  {
    "id": "DRV-89",
    "employeeId": "P00976",
    "name": "Hassan Umar Mamud",
    "phone": "08037055665",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-805283",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "P064 - GGE105YK",
    "currentTripId": null,
    "tripsCompleted": 28,
    "safetyScore": 80,
    "initials": "HU"
  },
  {
    "id": "DRV-90",
    "employeeId": "P00834",
    "name": "Ibrahim Hassan",
    "phone": "08155643758",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-623354",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P020 - JHN504XA",
    "currentTripId": null,
    "tripsCompleted": 27,
    "safetyScore": 90,
    "initials": "IH"
  },
  {
    "id": "DRV-91",
    "employeeId": "P00913",
    "name": "Sanusi Abdullahi",
    "phone": "08034778605",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-333448",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "P062 - GGE98YK",
    "currentTripId": null,
    "tripsCompleted": 28,
    "safetyScore": 91,
    "initials": "SA"
  },
  {
    "id": "DRV-92",
    "employeeId": "P00771",
    "name": "Yahaya Alabi Moruf",
    "phone": "08155643758",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-413036",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 4,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 10,
    "safetyScore": 86,
    "initials": "YA"
  },
  {
    "id": "DRV-93",
    "employeeId": "DRV-93",
    "name": "Abdullahi Ahmad",
    "phone": "08054110004",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-224955",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 6,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 21,
    "safetyScore": 98,
    "initials": "AA"
  },
  {
    "id": "DRV-94",
    "employeeId": "P00923",
    "name": "Tijani Lawal Abba",
    "phone": "08080... (truncated in scan)",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-478203",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 28,
    "safetyScore": 81,
    "initials": "TL"
  },
  {
    "id": "DRV-95",
    "employeeId": "P00905",
    "name": "Hussein Yinusa",
    "phone": "09048999210",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-148670",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 11,
    "status": "Available",
    "assignedTruck": "P037 - RJA343XA",
    "currentTripId": null,
    "tripsCompleted": 28,
    "safetyScore": 95,
    "initials": "HY"
  },
  {
    "id": "DRV-96",
    "employeeId": "P00973",
    "name": "Samaila Ibrahim",
    "phone": "07066163662",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-988512",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 11,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 47,
    "safetyScore": 89,
    "initials": "SI"
  },
  {
    "id": "DRV-97",
    "employeeId": "P01017",
    "name": "Ali Umar",
    "phone": "08137429141",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-384450",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 44,
    "safetyScore": 96,
    "initials": "AU"
  },
  {
    "id": "DRV-98",
    "employeeId": "P00860",
    "name": "Ibrahim Aliyu",
    "phone": "07067252236",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-555440",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P048 - GGE86YK",
    "currentTripId": null,
    "tripsCompleted": 24,
    "safetyScore": 99,
    "initials": "IA"
  },
  {
    "id": "DRV-99",
    "employeeId": "P01011",
    "name": "Abba Mohammed",
    "phone": "09069690379",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-299533",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 8,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 6,
    "safetyScore": 98,
    "initials": "AM"
  },
  {
    "id": "DRV-100",
    "employeeId": "P00904",
    "name": "Nasiru Aminu",
    "phone": "09030042258",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-310426",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "P059 - GGE91YK",
    "currentTripId": null,
    "tripsCompleted": 35,
    "safetyScore": 91,
    "initials": "NA"
  },
  {
    "id": "DRV-101",
    "employeeId": "P00982",
    "name": "Hassan Mohammed",
    "phone": "08167736574",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-555083",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 5,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 35,
    "safetyScore": 86,
    "initials": "HM"
  },
  {
    "id": "DRV-102",
    "employeeId": "P00546",
    "name": "Rabiu Mohammed",
    "phone": "091119972893",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-191514",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 2,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 39,
    "safetyScore": 84,
    "initials": "RM"
  },
  {
    "id": "DRV-103",
    "employeeId": "P00839",
    "name": "Yahaya",
    "phone": "07058644392",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-268188",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 7,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 17,
    "safetyScore": 82,
    "initials": "Y"
  },
  {
    "id": "DRV-104",
    "employeeId": "P00850",
    "name": "Auwalu Musa",
    "phone": "08035958315",
    "department": "Fleet Operations",
    "dateJoined": "2024-01-01",
    "licenseNumber": "LIC-136312",
    "licenseCategory": "Class G",
    "licenseExpiry": "2026-12-31",
    "compliance": "Valid",
    "experienceYears": 9,
    "status": "Available",
    "assignedTruck": "Unassigned",
    "currentTripId": null,
    "tripsCompleted": 31,
    "safetyScore": 93,
    "initials": "AM"
  }
];

export const TRUCK_HEADS: TruckHead[] = [
  {
    "id": "P001",
    "registration": "EPE 903 FS",
    "type": "Pickup",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P002",
    "registration": "KSF 72 YF",
    "type": "Pickup",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P004",
    "registration": "FKJ753XR",
    "type": "Short Body",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P005",
    "registration": "SBG566XR",
    "type": "Short Body",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P007",
    "registration": "AAA494XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P009",
    "registration": "MUS10XB",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P011",
    "registration": "KSF928XQ",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P012",
    "registration": "KSF929XQ",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P014",
    "registration": "GML376XX",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P015",
    "registration": "SBG757ZY",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P016",
    "registration": "GGW145XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P017",
    "registration": "GRR171XA ",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P018",
    "registration": "JHN402XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P019",
    "registration": "JHN503XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P020",
    "registration": "JHN504XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P021",
    "registration": "JHN506XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P022",
    "registration": "ZAR513XM",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P023",
    "registration": "MKR508ZP",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P024",
    "registration": "MKA434XV",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P025",
    "registration": "MGN899ZJ",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P026",
    "registration": "BNG751ZF",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P027",
    "registration": "GML365XX",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P028",
    "registration": "GML368XX",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P029",
    "registration": "GRK177XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P030",
    "registration": "DKA317XQ",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P031",
    "registration": "DKA321XQ",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P032",
    "registration": "ZAR883XX",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P033",
    "registration": "SBG674XT",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P034",
    "registration": "MKA982XW",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P035",
    "registration": "BDA884XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P036",
    "registration": "BDA887XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P037",
    "registration": "RJA343XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P038",
    "registration": "RJA344XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P039",
    "registration": "RJA345XA",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P040",
    "registration": "KNT781XP",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P041",
    "registration": "KNT783XP",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P042",
    "registration": "KNT785XP",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P043",
    "registration": "KRD989YE",
    "type": "LOCAL",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P044",
    "registration": "GGE109YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P045",
    "registration": "GGE100YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P046",
    "registration": "GGE107YE",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P047",
    "registration": "GGE83YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P048",
    "registration": "GGE86YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P049",
    "registration": "GGE104YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P051",
    "registration": "GGE102YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P052",
    "registration": "GGE106YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P053",
    "registration": "GGE97YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P054",
    "registration": "GGE84YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P055",
    "registration": "GGE85YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P056",
    "registration": "GGE96YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P057",
    "registration": "GGE87YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P058",
    "registration": "GGE94YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P059",
    "registration": "GGE91YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P060",
    "registration": "GGE103YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P061",
    "registration": "GGE101YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P062",
    "registration": "GGE98YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P063",
    "registration": "GGE89YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P064",
    "registration": "GGE105YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P065",
    "registration": "GGE95YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P066",
    "registration": "GGE92YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P067",
    "registration": "GGE99YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P068",
    "registration": "GGE90YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P069",
    "registration": "GGE88YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P070",
    "registration": "GGE93YK",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P071",
    "registration": "APP858YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P073",
    "registration": "APP857YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P074",
    "registration": "APP861YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P075",
    "registration": "APP864YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P076",
    "registration": "APP863YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P077",
    "registration": "APP862YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P078",
    "registration": "KRD280YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P079",
    "registration": "APP860YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P080",
    "registration": "FST568YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P081",
    "registration": "FST570YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P082",
    "registration": "FST569YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P083",
    "registration": "FST567YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P084",
    "registration": "KRD279YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P085",
    "registration": "APP589YL",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P086",
    "registration": "MNY180XB",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P087",
    "registration": "KRD994YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P088",
    "registration": "KRD986YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P089",
    "registration": "KRD992YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P090",
    "registration": "KRD993YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P091",
    "registration": "KRD995YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P092",
    "registration": "KRD987YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P093",
    "registration": "KRD996YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P094",
    "registration": "KRD988YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P095",
    "registration": "KRD997YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P096",
    "registration": "KRD985YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P097",
    "registration": "KRD989YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P098",
    "registration": "KRD991YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P099",
    "registration": "KRD998YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P100",
    "registration": "KRD990YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P101",
    "registration": "KRD999YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P102",
    "registration": "AKD323YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P103",
    "registration": "AKD322YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P104",
    "registration": "KRD532YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P105",
    "registration": "AKD321YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P106",
    "registration": "KRD534YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P107",
    "registration": "AKD326YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P108",
    "registration": "AKD324YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P109",
    "registration": "AKD320YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P110",
    "registration": "AKD328YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P111",
    "registration": "AKD327YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P112",
    "registration": "AKD325YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P113",
    "registration": "KRD531YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P114",
    "registration": "KRD530YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P115",
    "registration": "AKD329YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P116",
    "registration": "KRD533YM",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P117",
    "registration": "KTU958YN",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P118",
    "registration": "KTU956YN",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P119",
    "registration": "KTU959YN",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P120",
    "registration": "KTU957YN",
    "type": "UPCOUNTRY",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "P999",
    "registration": "AGL496YN",
    "type": "Pickup",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  },
  {
    "id": "Petroline",
    "registration": "Saba",
    "type": "Factory",
    "make": "Unknown",
    "year": 2020,
    "status": "Available"
  }
];

export const TRUCK_TAILS: TruckTail[] = [];

export const TRUCKS = [
  ...TRUCK_HEADS.map(t => ({ ...t, type: "Head" as const })),
  ...TRUCK_TAILS.map(t => ({ ...t, type: "Tail" as const }))
];

const TRIP_STATUSES: Trip["status"][] = [
  "En Route", "En Route", "Loaded", "Offloading", "Returning", "Delayed",
  "Completed", "Completed", "Scheduled", "Stopped", "Awaiting Approval", "Awaiting Approval", "Approved for Dispatch"
];

export const TRIPS: Trip[] = [];

// Seed one manual Requested order from a PWA customer for demo purposes


export const FEATURED_TRIP_ID = "TRP-00842";










export const FUEL_REQUISITIONS: FuelRequisition[] = [];

const DEFECTS = [
  "Brake air leak", "Engine overheating", "Gearbox slipping", "Front tyre wear",
  "Faulty alternator", "Suspension noise", "Clutch failure", "Headlamp fault",
  "Coolant leak", "Turbo underboost", "Steering play", "Trailer light fault",
];
const MECHANICS = ["Idris Bako", "Chuka Nwosu", "Sola Adebayo", "Aminu Tijjani", "Victor Etim"];

export const WORK_ORDERS: WorkOrder[] = [];

const PARTS = [
  ["Brake Pad", "BRK", "Brakes"], ["Air Filter", "FLT", "Filters"],
  ["Oil Filter", "FLT", "Filters"], ["Clutch Plate", "CLT", "Transmission"],
  ["Shock Absorber", "SUS", "Suspension"], ["Alternator", "ELC", "Electrical"],
  ["Battery 200Ah", "ELC", "Electrical"], ["Tyre 315/80R22.5", "TYR", "Tyres"],
  ["Wheel Bearing", "BRG", "Drivetrain"], ["Fuel Injector", "ENG", "Engine"],
  ["Radiator Hose", "ENG", "Engine"], ["Gasket Set", "ENG", "Engine"],
  ["Headlamp Unit", "ELC", "Electrical"], ["Leaf Spring", "SUS", "Suspension"],
  ["Air Dryer Cartridge", "BRK", "Brakes"], ["Turbo Charger", "ENG", "Engine"],
  ["Prop Shaft", "DRV", "Drivetrain"], ["Diff Oil 20L", "LUB", "Lubricants"],
  ["Engine Oil 20L", "LUB", "Lubricants"], ["Coolant 20L", "LUB", "Lubricants"],
];

export const INVENTORY: InventoryItem[] = [];


export const INVENTORY_REQUISITIONS: InventoryRequisition[] = [];

export const PROCUREMENT_REQUESTS: ProcurementRequest[] = [];

export const EXPENSES: Expense[] = [];


export const GATE_ENTRIES: GateEntry[] = [];

export const NOTIFICATIONS: Notification[] = [];

export const CONVERSATIONS: Conversation[] = [];

export const AUDIT_LOGS: AuditLog[] = [];

export const ACTIVITY: ActivityEvent[] = [];

export const ALERTS: AlertItem[] = [];

export const USERS: User[] = [
  ["Super Admin", "Platform Admin", "Platform Administrator", "System"],
  ["Okwudili Fortune", "Transport Manager", "Transport Manager", "Executive"],
  ["Tunde Balogun", "Fleet Operations", "Fleet Operations", "Operations"],
  ["Adaeze Nwoke", "Fleet Operations", "Dispatcher", "Operations"],
  ["Musa Danjuma", "Customer Portals (External)", "Customer Portal Rep", "External Partner"],
  ["Chuka Nwosu", "Engineering", "Engineer", "Engineering"],
  ["Idris Bako", "Parts & Store", "Store Manager", "Engineering"],
  ["Grace Ile", "Accounts", "Accountant", "Accounts"],
  ["Bisi Adeleke", "HR", "HR Manager", "Human Resources"],
  ["Sgt. Peter Obi", "Security", "Security Officer", "Security"],
  ["Ngozi Umeh", "Fleet Operations", "Fleet Operations", "Operations"],
].map(([name, role, roleName, department], i) => ({
  id: `USR-${pad(i + 1, 4)}`,
  name: name as string,
  email: role === "Platform Admin" ? "admin@fleetopsx.com" : role === "Customer Portals (External)" ? `${(name as string).toLowerCase().replace(/[^a-z]+/g, ".")}@sabasteel.com` : `${(name as string).toLowerCase().replace(/[^a-z]+/g, ".")}@petroline.ng`,
  username: role === "Platform Admin" ? "admin" : `${(name as string).split(" ")[0]!.charAt(0).toLowerCase()}${(name as string).split(" ")[1]!.toLowerCase()}`,
  roles: [role as User["roles"][0]],
  roleNames: [roleName as string],
  department: department as string,
  status: i === 8 ? "Invited" : "Active",
  passwordResetRequired: i === 1,
  lastActive: `${int(1, 59)} min ago`,
  initials: (name as string).split(" ").map((p) => p[0]).join("").slice(0, 2),
  companyId: i === 0 ? undefined : "tnt_001",
  partnerCompanyName: role === "Customer Portals (External)" ? "Saba Steel" : undefined,
}));

// Give Okwudili Fortune multiple roles for testing
USERS[1]!.roles = ["Transport Manager", "HR"];
USERS[1]!.roleNames = ["Transport Manager", "HR Manager"];

export const ROLES: Role[] = [
  { key: "Transport Manager", name: "Transport Admin", description: "Super Admin. Oversees all operations across every department.", modules: ["All modules"], users: 1 },
  { key: "Fleet Operations", name: "Fleet Operations", description: "Responsible for dispatching vehicles and assigning trips.", modules: ["Fleet & Dispatch"], users: 7 },
  { key: "Diesel", name: "Fuel Management", description: "Manages all fuel-related workflows and consumption.", modules: ["Fuel"], users: 4 },
  { key: "Engineering", name: "Engineering and Maintenance", description: "Manages the workshop and vehicle defect reports.", modules: ["Engineering"], users: 5 },
  { key: "Parts & Store", name: "Parts and Store", description: "Handles all workshop inventory and spare parts.", modules: ["Inventory"], users: 3 },
  { key: "Accounts", name: "Accounts", description: "Handles operational financials and trip invoicing.", modules: ["Accounts", "Reports"], users: 4 },
  { key: "HR", name: "HR and Personnel", description: "Manages staff files and verifies driver licenses.", modules: ["Drivers & HR"], users: 2 },
  { key: "Security", name: "Security", description: "Uses the system strictly to scan and verify digital gate passes.", modules: ["Gate & Security"], users: 9 },
  { key: "Driver", name: "Drivers", description: "Mobile app for trip assignments, fuel receipts, and PODs.", modules: ["Trips"], users: 34 },
  { key: "Customer Portals (External)", name: "Customer Portal", description: "External portal to submit logistics requests.", modules: ["Sister Portal"], users: 12 },
];

export const CHART_UTILISATION = [
  { label: "Mon", utilisation: 0, target: 80 },
  { label: "Tue", utilisation: 0, target: 80 },
  { label: "Wed", utilisation: 0, target: 80 },
  { label: "Thu", utilisation: 0, target: 80 },
  { label: "Fri", utilisation: 0, target: 80 },
  { label: "Sat", utilisation: 0, target: 80 },
  { label: "Sun", utilisation: 0, target: 80 },
];

export const CHART_TRIP_PERFORMANCE = [
  { label: "Wk 28", completed: 0, delayed: 0 },
  { label: "Wk 29", completed: 0, delayed: 0 },
  { label: "Wk 30", completed: 0, delayed: 0 },
  { label: "Wk 31", completed: 0, delayed: 0 },
  { label: "Wk 32", completed: 0, delayed: 0 },
  { label: "Wk 33", completed: 0, delayed: 0 },
];

export const CHART_FUEL = [
  { label: "Wk 28", actual: 0, standard: 0 },
  { label: "Wk 29", actual: 0, standard: 0 },
  { label: "Wk 30", actual: 0, standard: 0 },
  { label: "Wk 31", actual: 0, standard: 0 },
  { label: "Wk 32", actual: 0, standard: 0 },
  { label: "Wk 33", actual: 0, standard: 0 },
];

export const CHART_EXPENSE_SPLIT = [];

export const CHART_COST_REVENUE = [
  { label: "Mar", revenue: 0, cost: 0 },
  { label: "Apr", revenue: 0, cost: 0 },
  { label: "May", revenue: 0, cost: 0 },
  { label: "Jun", revenue: 0, cost: 0 },
  { label: "Jul", revenue: 0, cost: 0 },
  { label: "Aug", revenue: 0, cost: 0 },
];

import type { LoginReport } from "./types";
export const LOGIN_REPORTS: LoginReport[] = [];

