/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SisterCompanyRouteImport } from './routes/sister-company'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppDepreciationRouteImport } from './routes/app.depreciation'
import { Route as AppDispatchRouteImport } from './routes/app.dispatch'
import { Route as AppEngineeringRouteImport } from './routes/app.engineering'
import { Route as AppFleetRouteImport } from './routes/app.fleet'
import { Route as AppGateRouteImport } from './routes/app.gate'
import { Route as AppGodViewRouteImport } from './routes/app.god-view'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProcurementRouteImport } from './routes/app.procurement'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppUnauthorizedRouteImport } from './routes/app.unauthorized'
import { Route as PwaTenantIdRouteImport } from './routes/pwa.$tenantId'
import { Route as SisterCompanyIndexRouteImport } from './routes/sister-company.index'
import { Route as SisterCompanyRequestRouteImport } from './routes/sister-company.request'
import { Route as AppDriversIndexRouteImport } from './routes/app.drivers.index'
import { Route as AppDriversDriverIdRouteImport } from './routes/app.drivers.$driverId'
import { Route as AppTripsIndexRouteImport } from './routes/app.trips.index'
import { Route as AppTripsTripIdRouteImport } from './routes/app.trips.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SisterCompanyRoute = SisterCompanyRouteImport.update({
  id: '/sister-company',
  path: '/sister-company',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppDepreciationRoute = AppDepreciationRouteImport.update({
  id: '/depreciation',
  path: '/depreciation',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppEngineeringRoute = AppEngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppGateRoute = AppGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => AppRoute,
} as any)
const AppGodViewRoute = AppGodViewRouteImport.update({
  id: '/god-view',
  path: '/god-view',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppUnauthorizedRoute = AppUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRoute,
} as any)
const PwaTenantIdRoute = PwaTenantIdRouteImport.update({
  id: '/pwa/$tenantId',
  path: '/pwa/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const SisterCompanyIndexRoute = SisterCompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SisterCompanyRoute,
} as any)
const SisterCompanyRequestRoute = SisterCompanyRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => SisterCompanyRoute,
} as any)
const AppDriversIndexRoute = AppDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversDriverIdRoute = AppDriversDriverIdRouteImport.update({
  id: '/drivers/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsIndexRoute = AppTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsTripIdRoute = AppTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sister-company': typeof SisterCompanyRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/depreciation': typeof AppDepreciationRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/engineering': typeof AppEngineeringRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/gate': typeof AppGateRoute
  '/app/god-view': typeof AppGodViewRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/pwa/$tenantId': typeof PwaTenantIdRoute
  '/sister-company/request': typeof SisterCompanyRequestRoute
  '/app/': typeof AppIndexRoute
  '/sister-company/': typeof SisterCompanyIndexRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/trips/$tripId': typeof AppTripsTripIdRoute
  '/app/drivers/': typeof AppDriversIndexRoute
  '/app/trips/': typeof AppTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/depreciation': typeof AppDepreciationRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/engineering': typeof AppEngineeringRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/gate': typeof AppGateRoute
  '/app/god-view': typeof AppGodViewRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/pwa/$tenantId': typeof PwaTenantIdRoute
  '/sister-company/request': typeof SisterCompanyRequestRoute
  '/app': typeof AppIndexRoute
  '/sister-company': typeof SisterCompanyIndexRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/trips/$tripId': typeof AppTripsTripIdRoute
  '/app/drivers': typeof AppDriversIndexRoute
  '/app/trips': typeof AppTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sister-company': typeof SisterCompanyRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/depreciation': typeof AppDepreciationRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/engineering': typeof AppEngineeringRoute
  '/app/fleet': typeof AppFleetRoute
  '/app/gate': typeof AppGateRoute
  '/app/god-view': typeof AppGodViewRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/pwa/$tenantId': typeof PwaTenantIdRoute
  '/sister-company/request': typeof SisterCompanyRequestRoute
  '/app/': typeof AppIndexRoute
  '/sister-company/': typeof SisterCompanyIndexRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/trips/$tripId': typeof AppTripsTripIdRoute
  '/app/drivers/': typeof AppDriversIndexRoute
  '/app/trips/': typeof AppTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/sister-company'
    | '/superadmin'
    | '/app/accounts'
    | '/app/admin'
    | '/app/audit'
    | '/app/compliance'
    | '/app/depreciation'
    | '/app/dispatch'
    | '/app/engineering'
    | '/app/fleet'
    | '/app/gate'
    | '/app/god-view'
    | '/app/inventory'
    | '/app/messages'
    | '/app/notifications'
    | '/app/procurement'
    | '/app/reports'
    | '/app/unauthorized'
    | '/pwa/$tenantId'
    | '/sister-company/request'
    | '/app/'
    | '/sister-company/'
    | '/app/drivers/$driverId'
    | '/app/trips/$tripId'
    | '/app/drivers/'
    | '/app/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/superadmin'
    | '/app/accounts'
    | '/app/admin'
    | '/app/audit'
    | '/app/compliance'
    | '/app/depreciation'
    | '/app/dispatch'
    | '/app/engineering'
    | '/app/fleet'
    | '/app/gate'
    | '/app/god-view'
    | '/app/inventory'
    | '/app/messages'
    | '/app/notifications'
    | '/app/procurement'
    | '/app/reports'
    | '/app/unauthorized'
    | '/pwa/$tenantId'
    | '/sister-company/request'
    | '/app'
    | '/sister-company'
    | '/app/drivers/$driverId'
    | '/app/trips/$tripId'
    | '/app/drivers'
    | '/app/trips'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/sister-company'
    | '/superadmin'
    | '/app/accounts'
    | '/app/admin'
    | '/app/audit'
    | '/app/compliance'
    | '/app/depreciation'
    | '/app/dispatch'
    | '/app/engineering'
    | '/app/fleet'
    | '/app/gate'
    | '/app/god-view'
    | '/app/inventory'
    | '/app/messages'
    | '/app/notifications'
    | '/app/procurement'
    | '/app/reports'
    | '/app/unauthorized'
    | '/pwa/$tenantId'
    | '/sister-company/request'
    | '/app/'
    | '/sister-company/'
    | '/app/drivers/$driverId'
    | '/app/trips/$tripId'
    | '/app/drivers/'
    | '/app/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SisterCompanyRoute: typeof SisterCompanyRouteWithChildren
  SuperadminRoute: typeof SuperadminRoute
  PwaTenantIdRoute: typeof PwaTenantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sister-company': {
      id: '/sister-company'
      path: '/sister-company'
      fullPath: '/sister-company'
      preLoaderRoute: typeof SisterCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/depreciation': {
      id: '/app/depreciation'
      path: '/depreciation'
      fullPath: '/app/depreciation'
      preLoaderRoute: typeof AppDepreciationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatch': {
      id: '/app/dispatch'
      path: '/dispatch'
      fullPath: '/app/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/engineering': {
      id: '/app/engineering'
      path: '/engineering'
      fullPath: '/app/engineering'
      preLoaderRoute: typeof AppEngineeringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fleet': {
      id: '/app/fleet'
      path: '/fleet'
      fullPath: '/app/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gate': {
      id: '/app/gate'
      path: '/gate'
      fullPath: '/app/gate'
      preLoaderRoute: typeof AppGateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/god-view': {
      id: '/app/god-view'
      path: '/god-view'
      fullPath: '/app/god-view'
      preLoaderRoute: typeof AppGodViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procurement': {
      id: '/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unauthorized': {
      id: '/app/unauthorized'
      path: '/unauthorized'
      fullPath: '/app/unauthorized'
      preLoaderRoute: typeof AppUnauthorizedRouteImport
      parentRoute: typeof AppRoute
    }
    '/pwa/$tenantId': {
      id: '/pwa/$tenantId'
      path: '/pwa/$tenantId'
      fullPath: '/pwa/$tenantId'
      preLoaderRoute: typeof PwaTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sister-company/': {
      id: '/sister-company/'
      path: '/'
      fullPath: '/sister-company/'
      preLoaderRoute: typeof SisterCompanyIndexRouteImport
      parentRoute: typeof SisterCompanyRoute
    }
    '/sister-company/request': {
      id: '/sister-company/request'
      path: '/request'
      fullPath: '/sister-company/request'
      preLoaderRoute: typeof SisterCompanyRequestRouteImport
      parentRoute: typeof SisterCompanyRoute
    }
    '/app/drivers/': {
      id: '/app/drivers/'
      path: '/drivers'
      fullPath: '/app/drivers/'
      preLoaderRoute: typeof AppDriversIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drivers/$driverId': {
      id: '/app/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/app/drivers/$driverId'
      preLoaderRoute: typeof AppDriversDriverIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trips/': {
      id: '/app/trips/'
      path: '/trips'
      fullPath: '/app/trips/'
      preLoaderRoute: typeof AppTripsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trips/$tripId': {
      id: '/app/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/app/trips/$tripId'
      preLoaderRoute: typeof AppTripsTripIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAuditRoute: typeof AppAuditRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDepreciationRoute: typeof AppDepreciationRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppEngineeringRoute: typeof AppEngineeringRoute
  AppFleetRoute: typeof AppFleetRoute
  AppGateRoute: typeof AppGateRoute
  AppGodViewRoute: typeof AppGodViewRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppReportsRoute: typeof AppReportsRoute
  AppUnauthorizedRoute: typeof AppUnauthorizedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDriversDriverIdRoute: typeof AppDriversDriverIdRoute
  AppTripsTripIdRoute: typeof AppTripsTripIdRoute
  AppDriversIndexRoute: typeof AppDriversIndexRoute
  AppTripsIndexRoute: typeof AppTripsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAdminRoute: AppAdminRoute,
  AppAuditRoute: AppAuditRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDepreciationRoute: AppDepreciationRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppEngineeringRoute: AppEngineeringRoute,
  AppFleetRoute: AppFleetRoute,
  AppGateRoute: AppGateRoute,
  AppGodViewRoute: AppGodViewRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppReportsRoute: AppReportsRoute,
  AppUnauthorizedRoute: AppUnauthorizedRoute,
  AppIndexRoute: AppIndexRoute,
  AppDriversDriverIdRoute: AppDriversDriverIdRoute,
  AppTripsTripIdRoute: AppTripsTripIdRoute,
  AppDriversIndexRoute: AppDriversIndexRoute,
  AppTripsIndexRoute: AppTripsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SisterCompanyRouteChildren {
  SisterCompanyRequestRoute: typeof SisterCompanyRequestRoute
  SisterCompanyIndexRoute: typeof SisterCompanyIndexRoute
}

const SisterCompanyRouteChildren: SisterCompanyRouteChildren = {
  SisterCompanyRequestRoute: SisterCompanyRequestRoute,
  SisterCompanyIndexRoute: SisterCompanyIndexRoute,
}

const SisterCompanyRouteWithChildren = SisterCompanyRoute._addFileChildren(
  SisterCompanyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SisterCompanyRoute: SisterCompanyRouteWithChildren,
  SuperadminRoute: SuperadminRoute,
  PwaTenantIdRoute: PwaTenantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
