/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin.login'
import { Route as WorkspaceAccountTypeRouteImport } from './routes/workspace.account-type'
import { Route as WorkspaceAppRouteImport } from './routes/workspace.app'
import { Route as WorkspaceCustomerPortalRouteImport } from './routes/workspace.customer-portal'
import { Route as WorkspaceForgotPasswordRouteImport } from './routes/workspace.forgot-password'
import { Route as WorkspaceLoginRouteImport } from './routes/workspace.login'
import { Route as WorkspaceAppIndexRouteImport } from './routes/workspace.app.index'
import { Route as WorkspaceAppAccountsRouteImport } from './routes/workspace.app.accounts'
import { Route as WorkspaceAppAddAccountRouteImport } from './routes/workspace.app.add-account'
import { Route as WorkspaceAppAddPartnerRouteImport } from './routes/workspace.app.add-partner'
import { Route as WorkspaceAppAdminRouteImport } from './routes/workspace.app.admin'
import { Route as WorkspaceAppAuditRouteImport } from './routes/workspace.app.audit'
import { Route as WorkspaceAppComplianceRouteImport } from './routes/workspace.app.compliance'
import { Route as WorkspaceAppDepreciationRouteImport } from './routes/workspace.app.depreciation'
import { Route as WorkspaceAppDispatchRouteImport } from './routes/workspace.app.dispatch'
import { Route as WorkspaceAppEngineeringRouteImport } from './routes/workspace.app.engineering'
import { Route as WorkspaceAppFleetRouteImport } from './routes/workspace.app.fleet'
import { Route as WorkspaceAppGateRouteImport } from './routes/workspace.app.gate'
import { Route as WorkspaceAppGodViewRouteImport } from './routes/workspace.app.god-view'
import { Route as WorkspaceAppInventoryRouteImport } from './routes/workspace.app.inventory'
import { Route as WorkspaceAppManageAccountRouteImport } from './routes/workspace.app.manage-account'
import { Route as WorkspaceAppManagePartnerRouteImport } from './routes/workspace.app.manage-partner'
import { Route as WorkspaceAppMessagesRouteImport } from './routes/workspace.app.messages'
import { Route as WorkspaceAppNotificationsRouteImport } from './routes/workspace.app.notifications'
import { Route as WorkspaceAppPasswordRequestRouteImport } from './routes/workspace.app.password-request'
import { Route as WorkspaceAppReportsRouteImport } from './routes/workspace.app.reports'
import { Route as WorkspaceAppUnauthorizedRouteImport } from './routes/workspace.app.unauthorized'
import { Route as WorkspaceCustomerPortalIndexRouteImport } from './routes/workspace.customer-portal.index'
import { Route as WorkspaceCustomerPortalAuthRouteImport } from './routes/workspace.customer-portal._auth'
import { Route as WorkspaceCustomerPortalLoginRouteImport } from './routes/workspace.customer-portal.login'
import { Route as WorkspaceAppDriversIndexRouteImport } from './routes/workspace.app.drivers.index'
import { Route as WorkspaceAppDriversDriverIdRouteImport } from './routes/workspace.app.drivers.$driverId'
import { Route as WorkspaceAppTripsIndexRouteImport } from './routes/workspace.app.trips.index'
import { Route as WorkspaceAppTripsTripIdRouteImport } from './routes/workspace.app.trips.$tripId'
import { Route as WorkspaceCustomerPortalAuthRequestIdRouteImport } from './routes/workspace.customer-portal._auth.$requestId'
import { Route as WorkspaceCustomerPortalAuthDashboardRouteImport } from './routes/workspace.customer-portal._auth.dashboard'
import { Route as WorkspaceCustomerPortalAuthRequestRouteImport } from './routes/workspace.customer-portal._auth.request'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperadminRoute,
} as any)
const WorkspaceAccountTypeRoute = WorkspaceAccountTypeRouteImport.update({
  id: '/account-type',
  path: '/account-type',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAppRoute = WorkspaceAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCustomerPortalRoute = WorkspaceCustomerPortalRouteImport.update({
  id: '/customer-portal',
  path: '/customer-portal',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceForgotPasswordRoute = WorkspaceForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceLoginRoute = WorkspaceLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAppIndexRoute = WorkspaceAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppAccountsRoute = WorkspaceAppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppAddAccountRoute = WorkspaceAppAddAccountRouteImport.update({
  id: '/add-account',
  path: '/add-account',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppAddPartnerRoute = WorkspaceAppAddPartnerRouteImport.update({
  id: '/add-partner',
  path: '/add-partner',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppAdminRoute = WorkspaceAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppAuditRoute = WorkspaceAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppComplianceRoute = WorkspaceAppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppDepreciationRoute =
  WorkspaceAppDepreciationRouteImport.update({
    id: '/depreciation',
    path: '/depreciation',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppDispatchRoute = WorkspaceAppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppEngineeringRoute = WorkspaceAppEngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppFleetRoute = WorkspaceAppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppGateRoute = WorkspaceAppGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppGodViewRoute = WorkspaceAppGodViewRouteImport.update({
  id: '/god-view',
  path: '/god-view',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppInventoryRoute = WorkspaceAppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppManageAccountRoute =
  WorkspaceAppManageAccountRouteImport.update({
    id: '/manage-account',
    path: '/manage-account',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppManagePartnerRoute =
  WorkspaceAppManagePartnerRouteImport.update({
    id: '/manage-partner',
    path: '/manage-partner',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppMessagesRoute = WorkspaceAppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppNotificationsRoute =
  WorkspaceAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppPasswordRequestRoute =
  WorkspaceAppPasswordRequestRouteImport.update({
    id: '/password-request',
    path: '/password-request',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppReportsRoute = WorkspaceAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppUnauthorizedRoute =
  WorkspaceAppUnauthorizedRouteImport.update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceCustomerPortalIndexRoute =
  WorkspaceCustomerPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceCustomerPortalRoute,
  } as any)
const WorkspaceCustomerPortalAuthRoute =
  WorkspaceCustomerPortalAuthRouteImport.update({
    id: '/_auth',
    getParentRoute: () => WorkspaceCustomerPortalRoute,
  } as any)
const WorkspaceCustomerPortalLoginRoute =
  WorkspaceCustomerPortalLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => WorkspaceCustomerPortalRoute,
  } as any)
const WorkspaceAppDriversIndexRoute =
  WorkspaceAppDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppDriversDriverIdRoute =
  WorkspaceAppDriversDriverIdRouteImport.update({
    id: '/drivers/$driverId',
    path: '/drivers/$driverId',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppTripsIndexRoute = WorkspaceAppTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppTripsTripIdRoute = WorkspaceAppTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceCustomerPortalAuthRequestIdRoute =
  WorkspaceCustomerPortalAuthRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => WorkspaceCustomerPortalAuthRoute,
  } as any)
const WorkspaceCustomerPortalAuthDashboardRoute =
  WorkspaceCustomerPortalAuthDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => WorkspaceCustomerPortalAuthRoute,
  } as any)
const WorkspaceCustomerPortalAuthRequestRoute =
  WorkspaceCustomerPortalAuthRequestRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => WorkspaceCustomerPortalAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/superadmin/login': typeof SuperadminLoginRoute
  '/workspace/account-type': typeof WorkspaceAccountTypeRoute
  '/workspace/app': typeof WorkspaceAppRouteWithChildren
  '/workspace/customer-portal': typeof WorkspaceCustomerPortalRouteWithChildren
  '/workspace/forgot-password': typeof WorkspaceForgotPasswordRoute
  '/workspace/login': typeof WorkspaceLoginRoute
  '/workspace/app/accounts': typeof WorkspaceAppAccountsRoute
  '/workspace/app/add-account': typeof WorkspaceAppAddAccountRoute
  '/workspace/app/add-partner': typeof WorkspaceAppAddPartnerRoute
  '/workspace/app/admin': typeof WorkspaceAppAdminRoute
  '/workspace/app/audit': typeof WorkspaceAppAuditRoute
  '/workspace/app/compliance': typeof WorkspaceAppComplianceRoute
  '/workspace/app/depreciation': typeof WorkspaceAppDepreciationRoute
  '/workspace/app/dispatch': typeof WorkspaceAppDispatchRoute
  '/workspace/app/engineering': typeof WorkspaceAppEngineeringRoute
  '/workspace/app/fleet': typeof WorkspaceAppFleetRoute
  '/workspace/app/gate': typeof WorkspaceAppGateRoute
  '/workspace/app/god-view': typeof WorkspaceAppGodViewRoute
  '/workspace/app/inventory': typeof WorkspaceAppInventoryRoute
  '/workspace/app/manage-account': typeof WorkspaceAppManageAccountRoute
  '/workspace/app/manage-partner': typeof WorkspaceAppManagePartnerRoute
  '/workspace/app/messages': typeof WorkspaceAppMessagesRoute
  '/workspace/app/notifications': typeof WorkspaceAppNotificationsRoute
  '/workspace/app/password-request': typeof WorkspaceAppPasswordRequestRoute
  '/workspace/app/reports': typeof WorkspaceAppReportsRoute
  '/workspace/app/unauthorized': typeof WorkspaceAppUnauthorizedRoute
  '/workspace/customer-portal/login': typeof WorkspaceCustomerPortalLoginRoute
  '/workspace/app/': typeof WorkspaceAppIndexRoute
  '/workspace/customer-portal/': typeof WorkspaceCustomerPortalIndexRoute
  '/workspace/app/drivers/$driverId': typeof WorkspaceAppDriversDriverIdRoute
  '/workspace/app/trips/$tripId': typeof WorkspaceAppTripsTripIdRoute
  '/workspace/customer-portal/$requestId': typeof WorkspaceCustomerPortalAuthRequestIdRoute
  '/workspace/customer-portal/dashboard': typeof WorkspaceCustomerPortalAuthDashboardRoute
  '/workspace/customer-portal/request': typeof WorkspaceCustomerPortalAuthRequestRoute
  '/workspace/app/drivers/': typeof WorkspaceAppDriversIndexRoute
  '/workspace/app/trips/': typeof WorkspaceAppTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/superadmin/login': typeof SuperadminLoginRoute
  '/workspace/account-type': typeof WorkspaceAccountTypeRoute
  '/workspace/forgot-password': typeof WorkspaceForgotPasswordRoute
  '/workspace/login': typeof WorkspaceLoginRoute
  '/workspace/app/accounts': typeof WorkspaceAppAccountsRoute
  '/workspace/app/add-account': typeof WorkspaceAppAddAccountRoute
  '/workspace/app/add-partner': typeof WorkspaceAppAddPartnerRoute
  '/workspace/app/admin': typeof WorkspaceAppAdminRoute
  '/workspace/app/audit': typeof WorkspaceAppAuditRoute
  '/workspace/app/compliance': typeof WorkspaceAppComplianceRoute
  '/workspace/app/depreciation': typeof WorkspaceAppDepreciationRoute
  '/workspace/app/dispatch': typeof WorkspaceAppDispatchRoute
  '/workspace/app/engineering': typeof WorkspaceAppEngineeringRoute
  '/workspace/app/fleet': typeof WorkspaceAppFleetRoute
  '/workspace/app/gate': typeof WorkspaceAppGateRoute
  '/workspace/app/god-view': typeof WorkspaceAppGodViewRoute
  '/workspace/app/inventory': typeof WorkspaceAppInventoryRoute
  '/workspace/app/manage-account': typeof WorkspaceAppManageAccountRoute
  '/workspace/app/manage-partner': typeof WorkspaceAppManagePartnerRoute
  '/workspace/app/messages': typeof WorkspaceAppMessagesRoute
  '/workspace/app/notifications': typeof WorkspaceAppNotificationsRoute
  '/workspace/app/password-request': typeof WorkspaceAppPasswordRequestRoute
  '/workspace/app/reports': typeof WorkspaceAppReportsRoute
  '/workspace/app/unauthorized': typeof WorkspaceAppUnauthorizedRoute
  '/workspace/customer-portal': typeof WorkspaceCustomerPortalIndexRoute
  '/workspace/customer-portal/login': typeof WorkspaceCustomerPortalLoginRoute
  '/workspace/app': typeof WorkspaceAppIndexRoute
  '/workspace/app/drivers/$driverId': typeof WorkspaceAppDriversDriverIdRoute
  '/workspace/app/trips/$tripId': typeof WorkspaceAppTripsTripIdRoute
  '/workspace/customer-portal/$requestId': typeof WorkspaceCustomerPortalAuthRequestIdRoute
  '/workspace/customer-portal/dashboard': typeof WorkspaceCustomerPortalAuthDashboardRoute
  '/workspace/customer-portal/request': typeof WorkspaceCustomerPortalAuthRequestRoute
  '/workspace/app/drivers': typeof WorkspaceAppDriversIndexRoute
  '/workspace/app/trips': typeof WorkspaceAppTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/superadmin/login': typeof SuperadminLoginRoute
  '/workspace/account-type': typeof WorkspaceAccountTypeRoute
  '/workspace/app': typeof WorkspaceAppRouteWithChildren
  '/workspace/customer-portal': typeof WorkspaceCustomerPortalRouteWithChildren
  '/workspace/forgot-password': typeof WorkspaceForgotPasswordRoute
  '/workspace/login': typeof WorkspaceLoginRoute
  '/workspace/app/accounts': typeof WorkspaceAppAccountsRoute
  '/workspace/app/add-account': typeof WorkspaceAppAddAccountRoute
  '/workspace/app/add-partner': typeof WorkspaceAppAddPartnerRoute
  '/workspace/app/admin': typeof WorkspaceAppAdminRoute
  '/workspace/app/audit': typeof WorkspaceAppAuditRoute
  '/workspace/app/compliance': typeof WorkspaceAppComplianceRoute
  '/workspace/app/depreciation': typeof WorkspaceAppDepreciationRoute
  '/workspace/app/dispatch': typeof WorkspaceAppDispatchRoute
  '/workspace/app/engineering': typeof WorkspaceAppEngineeringRoute
  '/workspace/app/fleet': typeof WorkspaceAppFleetRoute
  '/workspace/app/gate': typeof WorkspaceAppGateRoute
  '/workspace/app/god-view': typeof WorkspaceAppGodViewRoute
  '/workspace/app/inventory': typeof WorkspaceAppInventoryRoute
  '/workspace/app/manage-account': typeof WorkspaceAppManageAccountRoute
  '/workspace/app/manage-partner': typeof WorkspaceAppManagePartnerRoute
  '/workspace/app/messages': typeof WorkspaceAppMessagesRoute
  '/workspace/app/notifications': typeof WorkspaceAppNotificationsRoute
  '/workspace/app/password-request': typeof WorkspaceAppPasswordRequestRoute
  '/workspace/app/reports': typeof WorkspaceAppReportsRoute
  '/workspace/app/unauthorized': typeof WorkspaceAppUnauthorizedRoute
  '/workspace/customer-portal/_auth': typeof WorkspaceCustomerPortalAuthRouteWithChildren
  '/workspace/customer-portal/login': typeof WorkspaceCustomerPortalLoginRoute
  '/workspace/app/': typeof WorkspaceAppIndexRoute
  '/workspace/customer-portal/': typeof WorkspaceCustomerPortalIndexRoute
  '/workspace/app/drivers/$driverId': typeof WorkspaceAppDriversDriverIdRoute
  '/workspace/app/trips/$tripId': typeof WorkspaceAppTripsTripIdRoute
  '/workspace/customer-portal/_auth/$requestId': typeof WorkspaceCustomerPortalAuthRequestIdRoute
  '/workspace/customer-portal/_auth/dashboard': typeof WorkspaceCustomerPortalAuthDashboardRoute
  '/workspace/customer-portal/_auth/request': typeof WorkspaceCustomerPortalAuthRequestRoute
  '/workspace/app/drivers/': typeof WorkspaceAppDriversIndexRoute
  '/workspace/app/trips/': typeof WorkspaceAppTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/superadmin'
    | '/workspace'
    | '/superadmin/login'
    | '/workspace/account-type'
    | '/workspace/app'
    | '/workspace/customer-portal'
    | '/workspace/forgot-password'
    | '/workspace/login'
    | '/workspace/app/accounts'
    | '/workspace/app/add-account'
    | '/workspace/app/add-partner'
    | '/workspace/app/admin'
    | '/workspace/app/audit'
    | '/workspace/app/compliance'
    | '/workspace/app/depreciation'
    | '/workspace/app/dispatch'
    | '/workspace/app/engineering'
    | '/workspace/app/fleet'
    | '/workspace/app/gate'
    | '/workspace/app/god-view'
    | '/workspace/app/inventory'
    | '/workspace/app/manage-account'
    | '/workspace/app/manage-partner'
    | '/workspace/app/messages'
    | '/workspace/app/notifications'
    | '/workspace/app/password-request'
    | '/workspace/app/reports'
    | '/workspace/app/unauthorized'
    | '/workspace/customer-portal/login'
    | '/workspace/app/'
    | '/workspace/customer-portal/'
    | '/workspace/app/drivers/$driverId'
    | '/workspace/app/trips/$tripId'
    | '/workspace/customer-portal/$requestId'
    | '/workspace/customer-portal/dashboard'
    | '/workspace/customer-portal/request'
    | '/workspace/app/drivers/'
    | '/workspace/app/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/superadmin'
    | '/workspace'
    | '/superadmin/login'
    | '/workspace/account-type'
    | '/workspace/forgot-password'
    | '/workspace/login'
    | '/workspace/app/accounts'
    | '/workspace/app/add-account'
    | '/workspace/app/add-partner'
    | '/workspace/app/admin'
    | '/workspace/app/audit'
    | '/workspace/app/compliance'
    | '/workspace/app/depreciation'
    | '/workspace/app/dispatch'
    | '/workspace/app/engineering'
    | '/workspace/app/fleet'
    | '/workspace/app/gate'
    | '/workspace/app/god-view'
    | '/workspace/app/inventory'
    | '/workspace/app/manage-account'
    | '/workspace/app/manage-partner'
    | '/workspace/app/messages'
    | '/workspace/app/notifications'
    | '/workspace/app/password-request'
    | '/workspace/app/reports'
    | '/workspace/app/unauthorized'
    | '/workspace/customer-portal'
    | '/workspace/customer-portal/login'
    | '/workspace/app'
    | '/workspace/app/drivers/$driverId'
    | '/workspace/app/trips/$tripId'
    | '/workspace/customer-portal/$requestId'
    | '/workspace/customer-portal/dashboard'
    | '/workspace/customer-portal/request'
    | '/workspace/app/drivers'
    | '/workspace/app/trips'
  id:
    | '__root__'
    | '/'
    | '/superadmin'
    | '/workspace'
    | '/superadmin/login'
    | '/workspace/account-type'
    | '/workspace/app'
    | '/workspace/customer-portal'
    | '/workspace/forgot-password'
    | '/workspace/login'
    | '/workspace/app/accounts'
    | '/workspace/app/add-account'
    | '/workspace/app/add-partner'
    | '/workspace/app/admin'
    | '/workspace/app/audit'
    | '/workspace/app/compliance'
    | '/workspace/app/depreciation'
    | '/workspace/app/dispatch'
    | '/workspace/app/engineering'
    | '/workspace/app/fleet'
    | '/workspace/app/gate'
    | '/workspace/app/god-view'
    | '/workspace/app/inventory'
    | '/workspace/app/manage-account'
    | '/workspace/app/manage-partner'
    | '/workspace/app/messages'
    | '/workspace/app/notifications'
    | '/workspace/app/password-request'
    | '/workspace/app/reports'
    | '/workspace/app/unauthorized'
    | '/workspace/customer-portal/_auth'
    | '/workspace/customer-portal/login'
    | '/workspace/app/'
    | '/workspace/customer-portal/'
    | '/workspace/app/drivers/$driverId'
    | '/workspace/app/trips/$tripId'
    | '/workspace/customer-portal/_auth/$requestId'
    | '/workspace/customer-portal/_auth/dashboard'
    | '/workspace/customer-portal/_auth/request'
    | '/workspace/app/drivers/'
    | '/workspace/app/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/workspace/account-type': {
      id: '/workspace/account-type'
      path: '/account-type'
      fullPath: '/workspace/account-type'
      preLoaderRoute: typeof WorkspaceAccountTypeRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/app': {
      id: '/workspace/app'
      path: '/app'
      fullPath: '/workspace/app'
      preLoaderRoute: typeof WorkspaceAppRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/customer-portal': {
      id: '/workspace/customer-portal'
      path: '/customer-portal'
      fullPath: '/workspace/customer-portal'
      preLoaderRoute: typeof WorkspaceCustomerPortalRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/forgot-password': {
      id: '/workspace/forgot-password'
      path: '/forgot-password'
      fullPath: '/workspace/forgot-password'
      preLoaderRoute: typeof WorkspaceForgotPasswordRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/login': {
      id: '/workspace/login'
      path: '/login'
      fullPath: '/workspace/login'
      preLoaderRoute: typeof WorkspaceLoginRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/app/': {
      id: '/workspace/app/'
      path: '/'
      fullPath: '/workspace/app/'
      preLoaderRoute: typeof WorkspaceAppIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/accounts': {
      id: '/workspace/app/accounts'
      path: '/accounts'
      fullPath: '/workspace/app/accounts'
      preLoaderRoute: typeof WorkspaceAppAccountsRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/add-account': {
      id: '/workspace/app/add-account'
      path: '/add-account'
      fullPath: '/workspace/app/add-account'
      preLoaderRoute: typeof WorkspaceAppAddAccountRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/add-partner': {
      id: '/workspace/app/add-partner'
      path: '/add-partner'
      fullPath: '/workspace/app/add-partner'
      preLoaderRoute: typeof WorkspaceAppAddPartnerRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/admin': {
      id: '/workspace/app/admin'
      path: '/admin'
      fullPath: '/workspace/app/admin'
      preLoaderRoute: typeof WorkspaceAppAdminRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/audit': {
      id: '/workspace/app/audit'
      path: '/audit'
      fullPath: '/workspace/app/audit'
      preLoaderRoute: typeof WorkspaceAppAuditRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/compliance': {
      id: '/workspace/app/compliance'
      path: '/compliance'
      fullPath: '/workspace/app/compliance'
      preLoaderRoute: typeof WorkspaceAppComplianceRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/depreciation': {
      id: '/workspace/app/depreciation'
      path: '/depreciation'
      fullPath: '/workspace/app/depreciation'
      preLoaderRoute: typeof WorkspaceAppDepreciationRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/dispatch': {
      id: '/workspace/app/dispatch'
      path: '/dispatch'
      fullPath: '/workspace/app/dispatch'
      preLoaderRoute: typeof WorkspaceAppDispatchRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/engineering': {
      id: '/workspace/app/engineering'
      path: '/engineering'
      fullPath: '/workspace/app/engineering'
      preLoaderRoute: typeof WorkspaceAppEngineeringRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/fleet': {
      id: '/workspace/app/fleet'
      path: '/fleet'
      fullPath: '/workspace/app/fleet'
      preLoaderRoute: typeof WorkspaceAppFleetRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/gate': {
      id: '/workspace/app/gate'
      path: '/gate'
      fullPath: '/workspace/app/gate'
      preLoaderRoute: typeof WorkspaceAppGateRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/god-view': {
      id: '/workspace/app/god-view'
      path: '/god-view'
      fullPath: '/workspace/app/god-view'
      preLoaderRoute: typeof WorkspaceAppGodViewRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/inventory': {
      id: '/workspace/app/inventory'
      path: '/inventory'
      fullPath: '/workspace/app/inventory'
      preLoaderRoute: typeof WorkspaceAppInventoryRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/manage-account': {
      id: '/workspace/app/manage-account'
      path: '/manage-account'
      fullPath: '/workspace/app/manage-account'
      preLoaderRoute: typeof WorkspaceAppManageAccountRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/manage-partner': {
      id: '/workspace/app/manage-partner'
      path: '/manage-partner'
      fullPath: '/workspace/app/manage-partner'
      preLoaderRoute: typeof WorkspaceAppManagePartnerRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/messages': {
      id: '/workspace/app/messages'
      path: '/messages'
      fullPath: '/workspace/app/messages'
      preLoaderRoute: typeof WorkspaceAppMessagesRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/notifications': {
      id: '/workspace/app/notifications'
      path: '/notifications'
      fullPath: '/workspace/app/notifications'
      preLoaderRoute: typeof WorkspaceAppNotificationsRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/password-request': {
      id: '/workspace/app/password-request'
      path: '/password-request'
      fullPath: '/workspace/app/password-request'
      preLoaderRoute: typeof WorkspaceAppPasswordRequestRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/reports': {
      id: '/workspace/app/reports'
      path: '/reports'
      fullPath: '/workspace/app/reports'
      preLoaderRoute: typeof WorkspaceAppReportsRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/unauthorized': {
      id: '/workspace/app/unauthorized'
      path: '/unauthorized'
      fullPath: '/workspace/app/unauthorized'
      preLoaderRoute: typeof WorkspaceAppUnauthorizedRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/customer-portal/': {
      id: '/workspace/customer-portal/'
      path: '/'
      fullPath: '/workspace/customer-portal/'
      preLoaderRoute: typeof WorkspaceCustomerPortalIndexRouteImport
      parentRoute: typeof WorkspaceCustomerPortalRoute
    }
    '/workspace/customer-portal/_auth': {
      id: '/workspace/customer-portal/_auth'
      path: ''
      fullPath: '/workspace/customer-portal'
      preLoaderRoute: typeof WorkspaceCustomerPortalAuthRouteImport
      parentRoute: typeof WorkspaceCustomerPortalRoute
    }
    '/workspace/customer-portal/login': {
      id: '/workspace/customer-portal/login'
      path: '/login'
      fullPath: '/workspace/customer-portal/login'
      preLoaderRoute: typeof WorkspaceCustomerPortalLoginRouteImport
      parentRoute: typeof WorkspaceCustomerPortalRoute
    }
    '/workspace/app/drivers/': {
      id: '/workspace/app/drivers/'
      path: '/drivers'
      fullPath: '/workspace/app/drivers/'
      preLoaderRoute: typeof WorkspaceAppDriversIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/drivers/$driverId': {
      id: '/workspace/app/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/workspace/app/drivers/$driverId'
      preLoaderRoute: typeof WorkspaceAppDriversDriverIdRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/trips/': {
      id: '/workspace/app/trips/'
      path: '/trips'
      fullPath: '/workspace/app/trips/'
      preLoaderRoute: typeof WorkspaceAppTripsIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/app/trips/$tripId': {
      id: '/workspace/app/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/workspace/app/trips/$tripId'
      preLoaderRoute: typeof WorkspaceAppTripsTripIdRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/workspace/customer-portal/_auth/$requestId': {
      id: '/workspace/customer-portal/_auth/$requestId'
      path: '/$requestId'
      fullPath: '/workspace/customer-portal/$requestId'
      preLoaderRoute: typeof WorkspaceCustomerPortalAuthRequestIdRouteImport
      parentRoute: typeof WorkspaceCustomerPortalAuthRoute
    }
    '/workspace/customer-portal/_auth/dashboard': {
      id: '/workspace/customer-portal/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/workspace/customer-portal/dashboard'
      preLoaderRoute: typeof WorkspaceCustomerPortalAuthDashboardRouteImport
      parentRoute: typeof WorkspaceCustomerPortalAuthRoute
    }
    '/workspace/customer-portal/_auth/request': {
      id: '/workspace/customer-portal/_auth/request'
      path: '/request'
      fullPath: '/workspace/customer-portal/request'
      preLoaderRoute: typeof WorkspaceCustomerPortalAuthRequestRouteImport
      parentRoute: typeof WorkspaceCustomerPortalAuthRoute
    }
  }
}

interface SuperadminRouteChildren {
  SuperadminLoginRoute: typeof SuperadminLoginRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminLoginRoute: SuperadminLoginRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface WorkspaceAppRouteChildren {
  WorkspaceAppAccountsRoute: typeof WorkspaceAppAccountsRoute
  WorkspaceAppAddAccountRoute: typeof WorkspaceAppAddAccountRoute
  WorkspaceAppAddPartnerRoute: typeof WorkspaceAppAddPartnerRoute
  WorkspaceAppAdminRoute: typeof WorkspaceAppAdminRoute
  WorkspaceAppAuditRoute: typeof WorkspaceAppAuditRoute
  WorkspaceAppComplianceRoute: typeof WorkspaceAppComplianceRoute
  WorkspaceAppDepreciationRoute: typeof WorkspaceAppDepreciationRoute
  WorkspaceAppDispatchRoute: typeof WorkspaceAppDispatchRoute
  WorkspaceAppEngineeringRoute: typeof WorkspaceAppEngineeringRoute
  WorkspaceAppFleetRoute: typeof WorkspaceAppFleetRoute
  WorkspaceAppGateRoute: typeof WorkspaceAppGateRoute
  WorkspaceAppGodViewRoute: typeof WorkspaceAppGodViewRoute
  WorkspaceAppInventoryRoute: typeof WorkspaceAppInventoryRoute
  WorkspaceAppManageAccountRoute: typeof WorkspaceAppManageAccountRoute
  WorkspaceAppManagePartnerRoute: typeof WorkspaceAppManagePartnerRoute
  WorkspaceAppMessagesRoute: typeof WorkspaceAppMessagesRoute
  WorkspaceAppNotificationsRoute: typeof WorkspaceAppNotificationsRoute
  WorkspaceAppPasswordRequestRoute: typeof WorkspaceAppPasswordRequestRoute
  WorkspaceAppReportsRoute: typeof WorkspaceAppReportsRoute
  WorkspaceAppUnauthorizedRoute: typeof WorkspaceAppUnauthorizedRoute
  WorkspaceAppIndexRoute: typeof WorkspaceAppIndexRoute
  WorkspaceAppDriversDriverIdRoute: typeof WorkspaceAppDriversDriverIdRoute
  WorkspaceAppTripsTripIdRoute: typeof WorkspaceAppTripsTripIdRoute
  WorkspaceAppDriversIndexRoute: typeof WorkspaceAppDriversIndexRoute
  WorkspaceAppTripsIndexRoute: typeof WorkspaceAppTripsIndexRoute
}

const WorkspaceAppRouteChildren: WorkspaceAppRouteChildren = {
  WorkspaceAppAccountsRoute: WorkspaceAppAccountsRoute,
  WorkspaceAppAddAccountRoute: WorkspaceAppAddAccountRoute,
  WorkspaceAppAddPartnerRoute: WorkspaceAppAddPartnerRoute,
  WorkspaceAppAdminRoute: WorkspaceAppAdminRoute,
  WorkspaceAppAuditRoute: WorkspaceAppAuditRoute,
  WorkspaceAppComplianceRoute: WorkspaceAppComplianceRoute,
  WorkspaceAppDepreciationRoute: WorkspaceAppDepreciationRoute,
  WorkspaceAppDispatchRoute: WorkspaceAppDispatchRoute,
  WorkspaceAppEngineeringRoute: WorkspaceAppEngineeringRoute,
  WorkspaceAppFleetRoute: WorkspaceAppFleetRoute,
  WorkspaceAppGateRoute: WorkspaceAppGateRoute,
  WorkspaceAppGodViewRoute: WorkspaceAppGodViewRoute,
  WorkspaceAppInventoryRoute: WorkspaceAppInventoryRoute,
  WorkspaceAppManageAccountRoute: WorkspaceAppManageAccountRoute,
  WorkspaceAppManagePartnerRoute: WorkspaceAppManagePartnerRoute,
  WorkspaceAppMessagesRoute: WorkspaceAppMessagesRoute,
  WorkspaceAppNotificationsRoute: WorkspaceAppNotificationsRoute,
  WorkspaceAppPasswordRequestRoute: WorkspaceAppPasswordRequestRoute,
  WorkspaceAppReportsRoute: WorkspaceAppReportsRoute,
  WorkspaceAppUnauthorizedRoute: WorkspaceAppUnauthorizedRoute,
  WorkspaceAppIndexRoute: WorkspaceAppIndexRoute,
  WorkspaceAppDriversDriverIdRoute: WorkspaceAppDriversDriverIdRoute,
  WorkspaceAppTripsTripIdRoute: WorkspaceAppTripsTripIdRoute,
  WorkspaceAppDriversIndexRoute: WorkspaceAppDriversIndexRoute,
  WorkspaceAppTripsIndexRoute: WorkspaceAppTripsIndexRoute,
}

const WorkspaceAppRouteWithChildren = WorkspaceAppRoute._addFileChildren(
  WorkspaceAppRouteChildren,
)

interface WorkspaceCustomerPortalAuthRouteChildren {
  WorkspaceCustomerPortalAuthRequestIdRoute: typeof WorkspaceCustomerPortalAuthRequestIdRoute
  WorkspaceCustomerPortalAuthDashboardRoute: typeof WorkspaceCustomerPortalAuthDashboardRoute
  WorkspaceCustomerPortalAuthRequestRoute: typeof WorkspaceCustomerPortalAuthRequestRoute
}

const WorkspaceCustomerPortalAuthRouteChildren: WorkspaceCustomerPortalAuthRouteChildren =
  {
    WorkspaceCustomerPortalAuthRequestIdRoute:
      WorkspaceCustomerPortalAuthRequestIdRoute,
    WorkspaceCustomerPortalAuthDashboardRoute:
      WorkspaceCustomerPortalAuthDashboardRoute,
    WorkspaceCustomerPortalAuthRequestRoute:
      WorkspaceCustomerPortalAuthRequestRoute,
  }

const WorkspaceCustomerPortalAuthRouteWithChildren =
  WorkspaceCustomerPortalAuthRoute._addFileChildren(
    WorkspaceCustomerPortalAuthRouteChildren,
  )

interface WorkspaceCustomerPortalRouteChildren {
  WorkspaceCustomerPortalAuthRoute: typeof WorkspaceCustomerPortalAuthRouteWithChildren
  WorkspaceCustomerPortalLoginRoute: typeof WorkspaceCustomerPortalLoginRoute
  WorkspaceCustomerPortalIndexRoute: typeof WorkspaceCustomerPortalIndexRoute
}

const WorkspaceCustomerPortalRouteChildren: WorkspaceCustomerPortalRouteChildren =
  {
    WorkspaceCustomerPortalAuthRoute:
      WorkspaceCustomerPortalAuthRouteWithChildren,
    WorkspaceCustomerPortalLoginRoute: WorkspaceCustomerPortalLoginRoute,
    WorkspaceCustomerPortalIndexRoute: WorkspaceCustomerPortalIndexRoute,
  }

const WorkspaceCustomerPortalRouteWithChildren =
  WorkspaceCustomerPortalRoute._addFileChildren(
    WorkspaceCustomerPortalRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceAccountTypeRoute: typeof WorkspaceAccountTypeRoute
  WorkspaceAppRoute: typeof WorkspaceAppRouteWithChildren
  WorkspaceCustomerPortalRoute: typeof WorkspaceCustomerPortalRouteWithChildren
  WorkspaceForgotPasswordRoute: typeof WorkspaceForgotPasswordRoute
  WorkspaceLoginRoute: typeof WorkspaceLoginRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAccountTypeRoute: WorkspaceAccountTypeRoute,
  WorkspaceAppRoute: WorkspaceAppRouteWithChildren,
  WorkspaceCustomerPortalRoute: WorkspaceCustomerPortalRouteWithChildren,
  WorkspaceForgotPasswordRoute: WorkspaceForgotPasswordRoute,
  WorkspaceLoginRoute: WorkspaceLoginRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
